import Head from 'next/head'
import Image from 'next/image'
import {Chango, Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Problem from "@/components/Problem/Problem";
import Choose from "@/components/Choose/Choose";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        <Problem/>
        <Choose/>
    </>
  )
}
