import Head from "next/head";
import Problem from "@/components/Problem/Problem";
import Choose from "@/components/Choose/Choose";
import Map from "@/components/Map/Map";
import Partner from "@/components/Partner/Partner";
import Quez from "@/components/Quez/Quez";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Statistics from "@/components/Statistics/Statistics";
import ConnectForm from "@/components/ConnectForm/ConnectForm";
import Price from "@/components/Price/Price";
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Statistics />
      <Problem />
      <ConnectForm />
      <Choose />
      <Price />
      <Map />
      <Partner />
      <Quez />
    </>
  );
}
